name: amazing_shoppingcart
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core:
  cloud_firestore:
  shared_preferences:
  json_annotation:
  flutter_bloc:
  equatable:
  injectable:
  get_it:
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:
  injectable_generator:
  mockito:
  pedantic: ^1.9.0


flutter:
  uses-material-design: true